version: '3.8'

services:
    e-commerce-app2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: e-commerce-app2
        restart: unless-stopped
        volumes:
            - .:/var/www/html
            - /home/webserver/uploads/e-commerce-uploads:/var/www/html/public/storage
        environment:
            APP_ENV: production
            APP_URL: https://e-commerce.smctgroup.ph
            DB_CONNECTION: mysql
            DB_HOST: 172.17.0.1
            DB_PORT: 3306
            DB_DATABASE: psaisv2
            DB_USERNAME: smct
            DB_PASSWORD: smct
        command: >
            sh -c "composer install --no-dev --optimize-autoloader &&
                   npm install &&
                   npm run build &&
                   php-fpm"
    e-commerce-nginx2:
        image: nginx:alpine
        container_name: e-commerce-nginx2
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - e-commerce-app
