version: '3.8'

services:
  e-commerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
        APP_ENV: production
        APP_URL: https://e-commerce.smctgroup.ph
        DB_CONNECTION: mysql
        DB_HOST: 172.17.0.1
        DB_PORT: 3306
        DB_DATABASE: psaisv2
        DB_USERNAME: smct
        DB_PASSWORD: smct
    networks:
      - e-commerce-network

  e-commerce-nginx:
    image: nginx:alpine
    container_name: e-commerce-nginx
    restart: unless-stopped
    ports:
      - "9003:9003"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - e-commerce-network
    depends_on:
      - e-commerce-app

networks:
  e-commerce-network:
    driver: bridge
