version: '3.8'

services:
  e-commerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-commerce-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - /home/webserver/uploads/e-commerce-uploads/public:/var/www/html/storage/app/public
    environment:
        APP_ENV: production
        APP_URL: https://e-commerce.smctgroup.ph
        DB_CONNECTION: mysql
        DB_HOST: 172.17.0.1
        DB_PORT: 3306
        DB_DATABASE: psaisv2
        DB_USERNAME: smct
        DB_PASSWORD: smct
        PUSHER_APP_ID: 1962323
        PUSHER_APP_KEY: 4a7679920b500c68c69c
        PUSHER_APP_SECRET: 1aaea6fab0da6050d8eb
        PUSHER_HOST: e-commerce.smctgroup.ph
        PUSHER_PORT: 443
        PUSHER_SCHEME: https
        PUSHER_APP_CLUSTER: ap1
    networks:
      - e-commerce-network

  e-commerce-nginx:
    image: nginx:alpine
    container_name: e-commerce-nginx
    restart: unless-stopped
    ports:
      - "9003:9003"
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php.ini:/usr/local/etc/php/php.ini
      - /home/webserver/uploads/e-commerce-uploads/public:/var/www/html/storage/app/public
    networks:
      - e-commerce-network
    depends_on:
      - e-commerce-app

networks:
  e-commerce-network:
    driver: bridge
